import type { Product } from '@/types/database';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'cali-t-original',
    name_fr: 'Cali-T Original',
    name_en: 'Cali-T Original',
    description_fr: 'Jus energisant 100% naturel a base de gingembre, bissap et petit cola. Booste votre systeme immunitaire et lutte contre la fatigue.',
    description_en: '100% natural energy juice made with ginger, hibiscus and petit cola. Boosts your immune system and fights fatigue.',
    benefits_fr: ['Booste le systeme immunitaire', 'Lutte contre la fatigue', 'Ameliore l\'endurance', 'Source d\'energie naturelle'],
    benefits_en: ['Boosts immune system', 'Fights fatigue', 'Improves endurance', 'Natural energy source'],
    ingredients_fr: 'Gingembre, Bissap, Petit colas, Sucre complet, Cocktail de fruits',
    ingredients_en: 'Ginger, Hibiscus, Petit cola, Whole sugar, Fruit cocktail',
    conservation_tips_fr: 'Conserver 5 jours au froid apres ouverture. Duree 1 mois.',
    conservation_tips_en: 'Keep refrigerated for 5 days after opening. Shelf life 1 month.',
    consumption_tips_fr: 'Servir glace pour une experience optimale',
    consumption_tips_en: 'Serve chilled for optimal experience',
    alcohol_option: true,
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [],
    formats: [
      { id: 'f1', product_id: '1', size: '25cl', price_fcfa: 500 },
      { id: 'f2', product_id: '1', size: '50cl', price_fcfa: 1000 },
      { id: 'f3', product_id: '1', size: '1L', price_fcfa: 2000 },
    ],
  },
  {
    id: '2',
    slug: 'cali-t-boost',
    name_fr: 'Cali-T Boost',
    name_en: 'Cali-T Boost',
    description_fr: 'Formule concentree pour un maximum d\'energie. Melange puissant de gingembre extra et d\'epices naturelles.',
    description_en: 'Concentrated formula for maximum energy. Powerful blend of extra ginger and natural spices.',
    benefits_fr: ['Energie maximale', 'Anti-inflammatoire', 'Digestion amelioree'],
    benefits_en: ['Maximum energy', 'Anti-inflammatory', 'Improved digestion'],
    ingredients_fr: 'Gingembre extra, Curcuma, Citron, Miel naturel',
    ingredients_en: 'Extra ginger, Turmeric, Lemon, Natural honey',
    conservation_tips_fr: 'Conserver au frais. Duree 3 semaines.',
    conservation_tips_en: 'Keep cool. Shelf life 3 weeks.',
    consumption_tips_fr: 'Consommer le matin a jeun pour de meilleurs resultats',
    consumption_tips_en: 'Consume in the morning on an empty stomach for best results',
    alcohol_option: false,
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [],
    formats: [
      { id: 'f4', product_id: '2', size: '25cl', price_fcfa: 500 },
      { id: 'f5', product_id: '2', size: '50cl', price_fcfa: 1000 },
      { id: 'f6', product_id: '2', size: '1L', price_fcfa: 2000 },
    ],
  },
  {
    id: '3',
    slug: 'cali-t-detox',
    name_fr: 'Cali-T Detox',
    name_en: 'Cali-T Detox',
    description_fr: 'Jus detoxifiant a base de fruits frais et d\'herbes locales. Purifie votre organisme naturellement.',
    description_en: 'Detoxifying juice made with fresh fruits and local herbs. Naturally purifies your body.',
    benefits_fr: ['Detoxification naturelle', 'Peau eclatante', 'Vitalite retrouvee'],
    benefits_en: ['Natural detoxification', 'Glowing skin', 'Renewed vitality'],
    ingredients_fr: 'Ananas, Concombre, Menthe, Citron vert, Gingembre',
    ingredients_en: 'Pineapple, Cucumber, Mint, Lime, Ginger',
    conservation_tips_fr: 'Conserver au refrigerateur. Consommer sous 5 jours.',
    conservation_tips_en: 'Keep refrigerated. Consume within 5 days.',
    consumption_tips_fr: 'Servir tres frais, ideal le matin',
    consumption_tips_en: 'Serve very cold, ideal in the morning',
    alcohol_option: true,
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [],
    formats: [
      { id: 'f7', product_id: '3', size: '25cl', price_fcfa: 500 },
      { id: 'f8', product_id: '3', size: '50cl', price_fcfa: 1000 },
      { id: 'f9', product_id: '3', size: '1L', price_fcfa: 2000 },
    ],
  },
];
